<?php

require_once dirname(__FILE__) . '/../../../../../app/F4h/TicketConverter/Dependency/Verifier.php';

/**
 * Test class for F4h_TicketConverter_Dependency_Verifier.
 * Generated by PHPUnit on 2012-01-09 at 14:01:11.
 */
class F4h_TicketConverter_Dependency_VerifierTest extends PHPUnit_Framework_TestCase
{

    protected $goodDependencies = array('xsl', 'curl');
    protected $badDependencies = array('curl', 'sdfsadfsfd');

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers F4h_TicketConverter_Dependency_Verifier::checkDependencies
     */
    public function testCheckDependencies()
    {
        //assert that loaded extension return true
        $this->assertTrue(F4h_TicketConverter_Dependency_Verifier::checkDependencies($this->goodDependencies));

        //assert no dependencies return true
        $this->assertTrue(F4h_TicketConverter_Dependency_Verifier::checkDependencies(array()));
        
        //assert that a not loaded extension causes an exception
        $this->assertInternalType($this->setExpectedException('F4h_TicketConverter_Dependency_Exception'), F4h_TicketConverter_Dependency_Verifier::checkDependencies($this->badDependencies));
        
    }
    
}

?>
