<?php

require_once dirname(__FILE__) . '/../../../../../app/F4h/TicketConverter/Data/Mapper.php';

/**
 * Test class for F4h_TicketConverter_Data_Mapper.
 * Generated by PHPUnit on 2012-01-09 at 15:34:35.
 */
class F4h_TicketConverter_Data_MapperTest extends PHPUnit_Framework_TestCase
{

    protected $testIds = array('4114', '4112');

    /**
     * @var F4h_TicketConverter_Data_Mapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $queue = $this->getMock('F4h_TicketConverter_Model_Queue');
        foreach ($this->testIds as $id) {
            $queue->enqueue($id);
        }
        $this->object = new F4h_TicketConverter_Data_Mapper($queue);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers F4h_TicketConverter_Data_Mapper::__construct
     */
    public function testConstruct()
    {
        
    }
    
    /**
     * @covers F4h_TicketConverter_Data_Mapper::map
     */
    public function testMap()
    {
        $returnValue = $this->object->map();
        $this->assertInstanceOf('F4h_TicketConverter_Model_Queue', $returnValue);
        
        foreach ($returnValue as $value)
        {
            $this->assertInstanceOf('F4h_TicketConverter_Model_Ticket', $value);
        }
    }

}

?>
