<?php

require_once dirname(__FILE__) . '/../../../../../../app/F4h/TicketConverter/QueueBuilder/Cli/Single.php';

/**
 * Test class for F4h_TicketConverter_QueueBuilder_Cli_Single.
 * Generated by PHPUnit on 2012-01-09 at 13:56:21.
 */
class F4h_TicketConverter_QueueBuilder_Cli_SingleTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var F4h_TicketConverter_QueueBuilder_Cli_Single
     */
    protected $object;

    public function provider()
    {
        return array(
            //one valid id
            array(4114, 'F4h_TicketConverter_Model_Queue'),
            //one invalid id
            array('bla', 'Exception'),
            //array of valid ids
            array(array(4114, 4112), 'F4h_TicketConverter_Model_Queue'),
            //array with one invalid id
            array(array(4114, 'bla'), 'F4h_TicketConverter_Model_Queue'),
            //array with invald ids
            array(array('blub', 'bla'), 'Exception')
        );
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers F4h_TicketConverter_QueueBuilder_Cli_Single::build
     * @dataProvider provider
     */
    public function testBuild($input, $expected)
    {
        $this->object = new F4h_TicketConverter_QueueBuilder_Cli_Single($input);

        if ($expected === 'Exception') {
            $this->assertInternalType($this->setExpectedException('F4h_TicketConverter_QueueBuilder_Exception'), $this->object->build());
        } else {
            $this->assertInstanceOf($expected, $this->object->build());
        }
    }

}

?>
