<?php

require_once dirname(__FILE__) . '/../../../../app/F4h/TicketConverter/Manager.php';

/**
 * Test class for F4h_TicketConverter_Manager.
 * Generated by PHPUnit on 2012-01-09 at 13:11:12.
 */
class F4h_TicketConverter_ManagerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var F4h_TicketConverter_Manager
     */
    protected $object;
    protected $queue;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->queue = $this->getMock('F4h_TicketConverter_Model_Queue');
        $this->object = new F4h_TicketConverter_Manager($this->queue);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers F4h_TicketConverter_Manager::getTicketQueue
     */
    public function testGetTicketQueueWithOneId()
    {
        $this->queue->enqueue('4114');

        $returnValue = $this->object->getTicketQueue();
        $this->assertInstanceOf('F4h_TicketConverter_Model_Queue', $returnValue);

        foreach ($returnValue as $value) {
            $this->assertInstanceOf('F4h_TicketConverter_Model_Ticket', $value);
        }
    }

    /**
     * @covers F4h_TicketConverter_Manager::getTicketQueue
     */
    public function testGetTicketQueueWithMoreIds()
    {
        $this->queue->enqueue('4114');
        $this->queue->enqueue('4112');

        $returnValue = $this->object->getTicketQueue();
        $this->assertInstanceOf('F4h_TicketConverter_Model_Queue', $returnValue);
        
        foreach ($returnValue as $value) {
            $this->assertInstanceOf('F4h_TicketConverter_Model_Ticket', $value);
        }
    }

    /**
     * @covers F4h_TicketConverter_Manager::getTicketQueue
     */
    public function testGetTicketQueueWithInvalid()
    {
        $returnValue = $this->object->getTicketQueue();
        $this->assertInstanceOf('F4h_TicketConverter_Model_Queue', $returnValue);
        
        $this->assertEmpty($returnValue->count());
    }

    /**
     * @covers F4h_TicketConverter_Manager::buildOutput
     * @todo Implement testStartProcess().
     */
    public function testBuildOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers F4h_TicketConverter_Manager::__destruct
     * @todo Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
