<?php

require_once dirname(__FILE__) . '/../../../../app/F4h/TicketConverter/Runner.php';

/**
 * Test class for F4h_TicketConverter_Runner.
 * Generated by PHPUnit on 2012-01-10 at 13:56:57.
 */
class F4h_TicketConverter_RunnerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var F4h_TicketConverter_Runner
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers F4h_TicketConverter_Runner::getMsgCollection
     */
    public function testGetMsgCollection()
    {
        self::assertInstanceOf('F4h_TicketConverter_Message_Collection', F4h_TicketConverter_Runner::getMsgContainer());
    }

    /**
     * @covers F4h_TicketConverter_Runner::go
     */
    public function testGo()
    {
        self::assertTrue(F4h_TicketConverter_Runner::go());
    }

}

?>
